global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    lab: prometheus

rule_files:
  - alert-rules.rules


scrape_configs:
  - job_name: Prometheus
    static_configs:
    - targets:
      - localhost:9090
      labels:
        grupo: "Prometheus"

  - job_name: Api
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - ""
      labels:
        grupo: "webapi"

  - job_name: MongoDBExporter
    static_configs:
    - targets:
      - mongodbexporter:9216
      labels:
        grupo: "MongoDB"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'